### ISSUE TITLE
"file" parameter is deprecated, use "data" instead

### ISSUE THREAD

**Issue by dotherightthing** [yakuhzi/github-release#3]
Deprecation warning:

```
Run yakuhzi/action-release@v1
  with:
    file: release.zip
  env:
    GITHUB_TOKEN: ***
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at /home/runner/work/_actions/yakuhzi/action-release/v1/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:13145:26
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as uploadReleaseAsset] (/home/runner/work/_actions/yakuhzi/action-release/v1/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:13142:26)
    at /home/runner/work/_actions/yakuhzi/action-release/v1/dist/main.js:78:29
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/yakuhzi/action-release/v1/dist/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/yakuhzi/action-release/v1/dist/main.js:4:12)
    at uploadAsset (/home/runner/work/_actions/yakuhzi/action-release/v1/dist/main.js:77:12)
    at /home/runner/work/_actions/yakuhzi/action-release/v1/dist/main.js:42:23 {
  name: 'Deprecation'
}
Release uploaded to ...
```

Config:

```
    - name: Upload release to the repository's Releases page
      uses: yakuhzi/action-release@v1
      with:
        file: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
